// js/features/accounting/reminder-module.js
// CDSDM 0.3.4 - UI Solleciti e promemoria scadenze

(function () {
  'use strict';
  window.AppModules = window.AppModules || {};
  window.AppModules.reminders = window.AppModules.reminders || {};
  let _bound = false;
  let _selectedKey = '';
  function esc(v) { return String(v == null ? '' : v).replace(/[&<>'\"]/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]; }); }
  function money(v) { const n = Number(v || 0); return Number.isFinite(n) ? n.toLocaleString('it-IT', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : '0,00'; }
  function getDataSafe(key) { if (typeof getData === 'function') return getData(key) || []; if (window.AppStore && typeof window.AppStore.get === 'function') return window.AppStore.get(key) || []; return (window.globalData && window.globalData[key]) || []; }
  function dataBundle() { return { customers: getDataSafe('customers'), suppliers: getDataSafe('suppliers'), invoices: getDataSafe('invoices'), purchases: getDataSafe('purchases'), reminderEvents: getDataSafe('reminderEvents') }; }
  function keyFor(it) { return [it.subjectType, it.subjectId, it.documentType, it.documentId].join('|'); }
  function levelBadge(level) { const map = { primo: 'text-bg-warning', secondo: 'text-bg-secondary', terzo: 'text-bg-danger' }; return '<span class="badge ' + (map[level] || 'text-bg-secondary') + '">' + esc(level || '-') + '</span>'; }
  function currentFilters() { return { subjectType: $('#reminder-subject-type').val() || 'all', level: $('#reminder-level').val() || 'all', status: $('#reminder-status').val() || 'overdue', text: $('#reminder-search').val() || '', today: $('#reminder-today').val() || '' }; }
  function currentItems() { if (!window.ReminderService) return []; const items = window.ReminderService.buildItems(dataBundle(), currentFilters()); window._lastReminderItems = items.slice(); return items; }
  function selectedItem() { const items = window._lastReminderItems || currentItems(); return items.find(function (it) { return keyFor(it) === _selectedKey; }) || items[0] || null; }
  function updatePreview() { const it = selectedItem(); if (!it || !window.ReminderService) { $('#reminder-preview').val(''); return; } _selectedKey = keyFor(it); $('#reminder-preview').val(window.ReminderService.buildReminderText(it, { companyInfo: getDataSafe('companyInfo') })); $('#reminder-selected-label').text((it.subjectName || '-') + ' · ' + (it.documentNumber || it.doc || it.documentId)); }
  function render() {
    if (!window.ReminderService) { $('#reminder-root').html('<div class="alert alert-danger">Servizio solleciti non disponibile.</div>'); return; }
    if (!$('#reminder-today').val()) $('#reminder-today').val(new Date().toISOString().slice(0,10));
    if (!$('#reminder-event-date').val()) $('#reminder-event-date').val(new Date().toISOString().slice(0,10));
    const items = currentItems(); const summary = window.ReminderService.summarize(items);
    $('#reminder-summary').html(['<div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="small text-muted">Scadenze filtrate</div><div class="fs-5 fw-bold">' + summary.count + '</div></div></div></div>', '<div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="small text-muted">Residuo aperto</div><div class="fs-5 fw-bold">€ ' + money(summary.residual) + '</div></div></div></div>', '<div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="small text-muted">Scadute</div><div class="fs-5 fw-bold text-danger">' + summary.overdueCount + '</div></div></div></div>', '<div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="small text-muted">Già sollecitate</div><div class="fs-5 fw-bold">' + summary.reminded + '</div></div></div></div>'].join(''));
    $('#reminder-level-summary').html('Livelli: primo ' + summary.firstLevel + ' · secondo ' + summary.secondLevel + ' · terzo ' + summary.thirdLevel);
    if (!items.length) { $('#reminder-table-body').html('<tr><td colspan="9" class="text-center text-muted py-4">Nessuna scadenza per i filtri selezionati.</td></tr>'); $('#reminder-preview').val(''); return; }
    if (!_selectedKey) _selectedKey = keyFor(items[0]);
    $('#reminder-table-body').html(items.map(function (it) { const k = keyFor(it); return '<tr class="' + (_selectedKey === k ? 'table-active' : '') + '"><td><button class="btn btn-sm btn-outline-primary reminder-select" data-key="' + esc(k) + '">Seleziona</button></td><td>' + esc(it.dueDate || '-') + '<div class="small text-muted">' + esc(it.daysLate || 0) + ' gg</div></td><td>' + esc(it.subjectType === 'supplier' ? 'Fornitore' : 'Cliente') + '</td><td>' + esc(it.subjectName || '-') + '</td><td>' + esc(it.documentNumber || it.doc || it.documentId) + '</td><td class="text-end">€ ' + money(it.residualAmount != null ? it.residualAmount : it.amount) + '</td><td>' + levelBadge(it.reminderLevel) + '</td><td class="text-center">' + esc(it.reminderCount || 0) + '</td><td>' + esc(it.lastReminderDate || '-') + '</td></tr>'; }).join(''));
    updatePreview();
  }
  async function saveReminder() { const it = selectedItem(); if (!it) { alert('Seleziona una scadenza da sollecitare.'); return; } const msg = $('#reminder-preview').val() || window.ReminderService.buildReminderText(it, { companyInfo: getDataSafe('companyInfo') }); const event = window.ReminderService.buildReminderEvent(it, msg, { date: $('#reminder-event-date').val() || new Date().toISOString().slice(0,10), channel: $('#reminder-channel').val() || 'email', status: $('#reminder-event-status').val() || 'preparato', notes: $('#reminder-notes').val() || '' }); if (typeof saveDataToCloud === 'function') await saveDataToCloud('reminderEvents', event, event.id); else { window.globalData = window.globalData || {}; window.globalData.reminderEvents = window.globalData.reminderEvents || []; window.globalData.reminderEvents.push(event); if (window.AppStore) window.AppStore.set('reminderEvents', window.globalData.reminderEvents); } alert('Sollecito registrato nello storico.'); render(); }
  function exportCsv() { const rows = currentItems(); const header = ['tipo','soggetto','documento','scadenza','giorni_ritardo','residuo','livello','numero_solleciti','ultimo_sollecito']; const csv = [header.join(';')].concat(rows.map(function (r) { return [r.subjectType, r.subjectName, r.documentNumber || r.doc, r.dueDate, r.daysLate, r.residualAmount, r.reminderLevel, r.reminderCount, r.lastReminderDate].map(function (v) { return '"' + String(v == null ? '' : v).replace(/"/g, '""') + '"'; }).join(';'); })).join('\n'); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'solleciti_scadenze_0_3_4.csv'; a.click(); URL.revokeObjectURL(a.href); }
  function copyPreview() { const text = $('#reminder-preview').val() || ''; if (navigator.clipboard && navigator.clipboard.writeText) navigator.clipboard.writeText(text).then(function(){ alert('Testo copiato negli appunti.'); }); else { $('#reminder-preview').trigger('select'); document.execCommand('copy'); alert('Testo copiato negli appunti.'); } }
  function bind() { if (_bound) return; _bound = true; $(document).on('change input', '#reminder-subject-type,#reminder-level,#reminder-status,#reminder-search,#reminder-today', function () { _selectedKey = ''; render(); }); $(document).on('click', '#reminder-reset-btn', function () { $('#reminder-subject-type').val('all'); $('#reminder-level').val('all'); $('#reminder-status').val('overdue'); $('#reminder-search').val(''); $('#reminder-today').val(new Date().toISOString().slice(0,10)); _selectedKey=''; render(); }); $(document).on('click', '.reminder-select', function () { _selectedKey = String($(this).data('key') || ''); render(); }); $(document).on('click', '#reminder-generate-btn', updatePreview); $(document).on('click', '#reminder-copy-btn', copyPreview); $(document).on('click', '#reminder-save-btn', saveReminder); $(document).on('click', '#reminder-export-csv-btn', exportCsv); }
  window.AppModules.reminders.render = render;
  window.AppModules.reminders.bind = bind;
})();
