// js/features/accounting/workflow-module.js
// CDSDM 0.4.2 - UI Workflow approvativi leggeri
(function () {
  'use strict';
  window.AppModules = window.AppModules || {};
  window.AppModules.workflow = window.AppModules.workflow || {};
  let _bound = false;
  function esc(v) { return String(v == null ? '' : v).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]); }
  function money(v) { return Number(v || 0).toFixed(2).replace('.', ','); }
  function getDataSafe(key) { if (window.AppStore && typeof window.AppStore.get === 'function') return window.AppStore.get(key) || []; if (typeof window.getData === 'function') return window.getData(key) || []; return (window.globalData && window.globalData[key]) || []; }
  function bundle() { return { quotes:getDataSafe('quotes'), customerOrders:getDataSafe('customerOrders'), supplierOrders:getDataSafe('supplierOrders'), customerDDTs:getDataSafe('customerDDTs'), supplierDDTs:getDataSafe('supplierDDTs'), invoices:getDataSafe('invoices'), purchases:getDataSafe('purchases'), notes:getDataSafe('notes'), paymentEvents:getDataSafe('paymentEvents'), bankReconciliationEvents:getDataSafe('bankReconciliationEvents'), workflowEvents:getDataSafe('workflowEvents'), customers:getDataSafe('customers'), suppliers:getDataSafe('suppliers') }; }
  function filters() { return { status: $('#workflow-filter-status').val() || 'open', type: $('#workflow-filter-type').val() || 'all', search: $('#workflow-search').val() || '' }; }
  function statusBadge(status, label) { const tone = { draft:'secondary', pending_review:'warning text-dark', approved:'success', rejected:'danger', blocked:'dark' }[status] || 'secondary'; return '<span class="badge bg-' + tone + '">' + esc(label || status) + '</span>'; }
  function priorityBadge(priority) { const tone = { danger:'danger', warning:'warning text-dark', info:'info text-dark', success:'success' }[priority] || 'secondary'; const label = { danger:'Alta', warning:'Media', info:'Normale', success:'OK' }[priority] || priority; return '<span class="badge bg-' + tone + '">' + esc(label) + '</span>'; }
  function card(label, value, hint, tone) { return '<div class="col-md-2 col-sm-4"><div class="card h-100 border-' + esc(tone || 'light') + '"><div class="card-body py-3"><div class="text-muted small">' + esc(label) + '</div><div class="fs-4 fw-semibold">' + esc(value) + '</div><div class="small text-muted">' + esc(hint || '') + '</div></div></div></div>'; }
  function renderSummary(s) { $('#workflow-summary').html([card('Attività',s.total||0,'filtri correnti','primary'), card('Da verificare',s.pending_review||0,'in revisione','warning'), card('Bloccate',s.blocked||0,'da sbloccare','dark'), card('Respinte',s.rejected||0,'da correggere','danger'), card('Approvate',s.approved||0,'incluse se filtrate','success'), card('Eventi',s.events||0,'storico workflow','info')].join('')); }
  function renderTable(tasks) { if (!tasks.length) { $('#workflow-table-body').html('<tr><td colspan="9" class="text-center text-muted py-4">Nessuna attività workflow per i filtri selezionati.</td></tr>'); return; } const disabled = window.PermissionsPolicy && window.PermissionsPolicy.canWrite && !window.PermissionsPolicy.canWrite('accounting'); const dis = disabled ? ' disabled' : ''; $('#workflow-table-body').html(tasks.map(t => '<tr><td>'+priorityBadge(t.priority)+'</td><td><div class="fw-semibold">'+esc(t.label)+'</div><div class="small text-muted">'+esc(t.number)+'</div></td><td>'+esc(t.date)+'</td><td>'+esc(t.subjectName)+'</td><td class="text-end">'+(Number(t.amount||0)?'€ '+money(t.amount):'')+'</td><td>'+statusBadge(t.workflowStatus,t.statusLabel)+'</td><td><div class="small">'+esc(t.suggestedAction)+'</div>'+(t.latestEvent?'<div class="small text-muted">Ultimo: '+esc(t.latestEvent.action)+' '+esc((t.latestEvent.createdAt||'').slice(0,10))+'</div>':'')+'</td><td><button class="btn btn-sm btn-outline-primary workflow-open-target" data-target="'+esc(t.targetSection)+'">'+esc(t.targetLabel||'Apri')+'</button></td><td><div class="btn-group btn-group-sm" role="group"><button class="btn btn-outline-success workflow-action" data-action="approve" data-task-id="'+esc(t.id)+'"'+dis+'>Approva</button><button class="btn btn-outline-warning workflow-action" data-action="review" data-task-id="'+esc(t.id)+'"'+dis+'>Revisione</button><button class="btn btn-outline-danger workflow-action" data-action="reject" data-task-id="'+esc(t.id)+'"'+dis+'>Respingi</button><button class="btn btn-outline-dark workflow-action" data-action="block" data-task-id="'+esc(t.id)+'"'+dis+'>Blocca</button></div></td></tr>').join('')); }
  function renderHistory(events) { const list = (events || []).slice().sort((a,b) => String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,20); $('#workflow-history').html(list.length ? list.map(e => '<div class="border-bottom py-2"><div class="d-flex justify-content-between"><strong>'+esc(e.sourceType)+' '+esc(e.sourceNumber||e.sourceId)+'</strong><span class="small text-muted">'+esc((e.createdAt||'').slice(0,16).replace('T',' '))+'</span></div><div class="small">'+esc(e.statusFrom)+' → '+esc(e.statusTo)+' · '+esc(e.createdBy||'')+'</div><div class="small text-muted">'+esc(e.note||'')+'</div></div>').join('') : '<div class="text-muted small">Nessun evento workflow registrato.</div>'); }
  function render() { if (!window.WorkflowService) { $('#workflow-status').html('<div class="alert alert-danger">WorkflowService non disponibile.</div>'); return; } const status = $('#workflow-filter-status').val() || 'open'; const result = window.WorkflowService.buildTasks(bundle(), { filters: filters(), includeApproved: status === 'all' || status === 'approved' }); window._lastWorkflowResult = result; renderSummary(result.summary); renderTable(result.tasks); renderHistory(result.events); $('#workflow-status').html('<div class="alert alert-light border small mb-0">Workflow 0.12.13: l\'approvazione rende operativi i documenti lavorabili, ad esempio ordini cliente/fornitore da Bozza a Confermato; gli eventi restano tracciati in <code>workflowEvents</code>.</div>'); }
  function openTarget(target) { if (!target) return; const link = $('.nav-link[data-target="' + target + '"]').first(); if (link.length) link.trigger('click'); }
  async function runAction(taskId, action) { const result = window._lastWorkflowResult || { tasks: [] }; const task = (result.tasks || []).find(t => t.id === taskId); if (!task) return alert('Attività non trovata.'); if (window.PermissionsPolicy && window.PermissionsPolicy.canWrite && !window.PermissionsPolicy.canWrite('accounting')) return alert('Ruolo non autorizzato alla modifica workflow.'); const note = $('#workflow-action-note').val() || ''; if (!confirm('Confermi azione workflow: ' + action + ' su ' + task.label + ' ' + task.number + '?')) return; try { await window.WorkflowService.applyAction(task, action, note); if (typeof window.loadAllDataFromCloud === 'function' && window.currentUser) await window.loadAllDataFromCloud(); render(); if (window.renderAll) window.renderAll(); } catch(e) { console.error(e); alert('Errore workflow: ' + (e && e.message ? e.message : e)); } }
  function csvCell(v) { const s = String(v == null ? '' : v).replace(/\r\n|\r|\n/g, ' ').trim(); return /[";\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; }
  function exportCsv() { const result = window._lastWorkflowResult || { tasks: [] }; const rows = window.WorkflowService.exportRows(result.tasks || []); const lines = [['Tipo','Numero','Data','Soggetto','Importo','Stato','Azione','Sezione'].join(';')]; rows.forEach(r => lines.push([r.tipo,r.numero,r.data,r.soggetto,money(r.importo),r.stato,r.azione,r.sezione].map(csvCell).join(';'))); const blob = new Blob([lines.join('\r\n')], { type:'text/csv;charset=utf-8' }); const a = document.createElement('a'); a.download = 'workflow_approvativi_042.csv'; a.href = URL.createObjectURL(blob); a.click(); URL.revokeObjectURL(a.href); }
  function bind() { if (_bound) return; _bound = true; $('#workflow-approvativi').on('click','#workflow-refresh-btn',render); $('#workflow-approvativi').on('change input','#workflow-filter-status,#workflow-filter-type,#workflow-search',render); $('#workflow-approvativi').on('click','#workflow-export-csv-btn',exportCsv); $('#workflow-approvativi').on('click','.workflow-open-target',function(){ openTarget($(this).data('target')); }); $('#workflow-approvativi').on('click','.workflow-action',function(){ runAction($(this).data('task-id'), $(this).data('action')); }); }
  window.AppModules.workflow.bind = bind;
  window.AppModules.workflow.render = render;
})();
