// js/features/warehouse/quotes-module.js
// Preventivi: anello iniziale del ciclo vendite Preventivo -> Ordine cliente -> DDT -> Fattura.
(function () {
  window.AppModules = window.AppModules || {};
  window.AppModules.quotes = window.AppModules.quotes || {};

  let _bound = false;
  let tempLines = [];
  let currentDetailId = null;

  const STATUS_LABELS = { draft:'Bozza', sent:'Inviato', accepted:'Accettato', rejected:'Rifiutato', converted:'Convertito', cancelled:'Annullato' };
  function esc(v){ if(window.VatRateCatalog&&typeof window.VatRateCatalog.escapeHtml==='function') return window.VatRateCatalog.escapeHtml(v); return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c];}); }
  function num(v){ const n=parseFloat(String(v==null?0:v).replace(',','.')); return isNaN(n)?0:n; }
  function fmtQty(v){ return num(v).toLocaleString('it-IT',{minimumFractionDigits:0,maximumFractionDigits:3}); }
  function fmtMoney(v){ return '€ '+num(v).toLocaleString('it-IT',{minimumFractionDigits:2,maximumFractionDigits:2}); }
  function today(){ return new Date().toISOString().slice(0,10); }
  function formatDate(v){ if(!v) return '-'; const p=String(v).slice(0,10).split('-'); return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:String(v); }
  function emptyState(title,hint){ return '<div class="warehouse-empty-state"><i class="fas fa-circle-info mb-2"></i><span class="empty-title">'+esc(title)+'</span><span class="empty-hint">'+esc(hint||'')+'</span></div>'; }
  function badgeClass(status){ if(status==='accepted') return 'text-bg-success'; if(status==='converted') return 'text-bg-primary'; if(status==='sent') return 'text-bg-info'; if(status==='rejected'||status==='cancelled') return 'text-bg-secondary'; return 'text-bg-light text-dark'; }
  function getStoreArray(key){ if(window.AppStore&&typeof window.AppStore.get==='function') return window.AppStore.get(key)||[]; if(typeof window.getData==='function') return window.getData(key)||[]; return (window.globalData&&window.globalData[key])||[]; }
  function normalizeQuote(q){ return window.DomainNormalizers&&typeof window.DomainNormalizers.normalizeQuote==='function' ? window.DomainNormalizers.normalizeQuote(q) : (q||{}); }
  function normalizeProduct(p){ return window.DomainNormalizers&&typeof window.DomainNormalizers.normalizeProductInfo==='function' ? window.DomainNormalizers.normalizeProductInfo(p) : (p||{}); }
  function getQuotes(){ return getStoreArray('quotes').map(normalizeQuote).sort(function(a,b){ return (String(b.date||'')+' '+String(b.number||'')).localeCompare(String(a.date||'')+' '+String(a.number||'')); }); }
  function getCustomers(){ return getStoreArray('customers')||[]; }
  function getProducts(){ return (getStoreArray('products')||[]).map(normalizeProduct).filter(function(p){ return p.itemType === 'product' || p.itemType === 'service'; }); }
  function getNextId(){ const ids=getStoreArray('quotes').map(function(q){return parseInt(q.id,10);}).filter(function(n){return !isNaN(n);}); return ids.length?Math.max.apply(null,ids)+1:1; }
  function getNextOrderId(){ const ids=getStoreArray('customerOrders').map(function(o){return parseInt(o.id,10);}).filter(function(n){return !isNaN(n);}); return ids.length?Math.max.apply(null,ids)+1:1; }
  function previewNumber(){ const y=new Date().getFullYear(); const max=getStoreArray('quotes').reduce(function(acc,q){ const n=String(q.number||q.numero||''); const m=n.match(/^PR-(\d{4})-(\d+)$/); return (m&&m[1]===String(y))?Math.max(acc,parseInt(m[2],10)||0):acc; },0); return 'PR-'+y+'-'+String(max+1).padStart(4,'0'); }
  function previewOrderNumber(){ const y=new Date().getFullYear(); const max=getStoreArray('customerOrders').reduce(function(acc,o){ const n=String(o.number||o.numero||''); const m=n.match(/^OC-(\d{4})-(\d+)$/); return (m&&m[1]===String(y))?Math.max(acc,parseInt(m[2],10)||0):acc; },0); return 'OC-'+y+'-'+String(max+1).padStart(4,'0'); }

  function renderCustomerOptions(){ const $sel=$('#quote-customerId'); if(!$sel.length) return; const cur=$sel.val(); $sel.empty().append('<option value="">Seleziona cliente...</option>'); getCustomers().forEach(function(c){ const label=c.name||c.nome||c.ragioneSociale||c.denominazione||c.email||('Cliente '+c.id); $sel.append('<option value="'+esc(c.id)+'">'+esc(label)+'</option>'); }); if(cur) $sel.val(cur); }
  function renderProductOptions(){ const $sel=$('#quote-productId'); if(!$sel.length) return; const cur=$sel.val(); $sel.empty().append('<option value="">Seleziona voce...</option>'); getProducts().forEach(function(p){ const label=(p.code?p.code+' - ':'')+(p.description||'Voce')+' · '+(p.itemType==='service'?'servizio':'prodotto'); $sel.append('<option value="'+esc(p.id)+'" data-price="'+esc(p.salePrice||p.price||0)+'">'+esc(label)+'</option>'); }); if(cur) $sel.val(cur); syncPrice(); }
  function syncPrice(){ const id=$('#quote-productId').val(); const p=getProducts().find(function(x){return String(x.id)===String(id);}); if(p && !$('#quote-linePrice').data('manual')) $('#quote-linePrice').val(num(p.salePrice||p.price||0).toFixed(2)); }
  function recalcLines(){ const $body=$('#quote-lines-body'); if(!$body.length) return; $body.empty(); if(!tempLines.length){ $body.append('<tr><td colspan="7" class="text-center text-muted py-3">Nessuna riga inserita.</td></tr>'); } else { tempLines.forEach(function(l,i){ $body.append('<tr><td>'+esc(l.productCode||'')+'</td><td>'+esc(l.productDescription||'')+'</td><td>'+esc(l.unitOfMeasure||'pz')+'</td><td class="text-end">'+fmtQty(l.qty)+'</td><td class="text-end">'+fmtMoney(l.price)+'</td><td class="text-end fw-semibold">'+fmtMoney(l.qty*l.price)+'</td><td class="text-end"><button class="btn btn-outline-danger quote-remove-line" data-index="'+i+'" type="button"><i class="fas fa-trash"></i></button></td></tr>'); }); } const total=tempLines.reduce(function(s,l){return s+num(l.qty)*num(l.price);},0); $('#quote-total').text(fmtMoney(total)); }
  function resetForm(){ const f=document.getElementById('quoteForm'); if(f) f.reset(); $('#quote-id').val(''); $('#quote-number').val(previewNumber()); $('#quote-date').val(today()); $('#quote-validUntil').val(''); $('#quote-status').val('draft'); tempLines=[]; renderCustomerOptions(); renderProductOptions(); $('#quote-lineQty').val('1'); $('#quote-linePrice').data('manual',false); recalcLines(); }
  function addLine(){ const productId=$('#quote-productId').val(); const qty=num($('#quote-lineQty').val()); const price=num($('#quote-linePrice').val()); if(!productId){ alert('Seleziona una voce.'); return; } if(qty<=0){ alert('Inserisci una quantità maggiore di zero.'); return; } const p=getProducts().find(function(x){return String(x.id)===String(productId);}); if(!p){ alert('Voce non trovata.'); return; } tempLines.push({ productId:String(p.id), productCode:p.code||'', productDescription:p.description||'', description:p.description||'', unitOfMeasure:p.unitOfMeasure||p.um||'pz', qty:qty, quotedQty:qty, price:price, salePrice:price, lineTotal:qty*price }); $('#quote-lineQty').val('1'); $('#quote-linePrice').data('manual',false); syncPrice(); recalcLines(); }
  async function saveQuote(){ const customerId=$('#quote-customerId').val(); const customer=getCustomers().find(function(c){return String(c.id)===String(customerId);}); if(!customer){ alert('Seleziona un cliente.'); return; } if(!tempLines.length){ alert('Aggiungi almeno una riga.'); return; } const id=String($('#quote-id').val()||getNextId()); const customerName=customer.name||customer.nome||customer.ragioneSociale||customer.denominazione||''; const now=new Date().toISOString(); const raw={ id:id, number:($('#quote-number').val()||previewNumber()).trim(), date:$('#quote-date').val()||today(), validUntil:$('#quote-validUntil').val()||'', customerId:String(customer.id), customerName:customerName, status:$('#quote-status').val()||'draft', lines:tempLines, notes:($('#quote-notes').val()||'').trim(), updatedAt:now }; if(!getStoreArray('quotes').some(function(q){return String(q.id)===id;})) raw.createdAt=now; const quote=normalizeQuote(raw); try{ $('#saveQuoteBtn').prop('disabled',true); await window.saveDataToCloud('quotes', quote, id); $('#quoteModal').modal('hide'); render(); } finally { $('#saveQuoteBtn').prop('disabled',false); } }
  function render(){ renderCustomerOptions(); renderProductOptions(); const $body=$('#quotes-table-body'); if(!$body.length) return; $body.empty(); const quotes=getQuotes(); if(!quotes.length){ $body.append('<tr><td colspan="8">'+emptyState('Nessun preventivo registrato','Crea un preventivo e convertilo in ordine cliente quando viene accettato.')+'</td></tr>'); return; } quotes.forEach(function(q){ const lines=(q.lines||[]).length; $body.append('<tr><td>'+esc(q.number||'-')+'</td><td>'+esc(formatDate(q.date))+'</td><td>'+esc(formatDate(q.validUntil))+'</td><td>'+esc(q.customerName||'-')+'</td><td><span class="badge warehouse-status-badge '+badgeClass(q.status)+'">'+esc(STATUS_LABELS[q.status]||q.status)+'</span></td><td class="text-end">'+lines+'</td><td class="text-end fw-semibold">'+fmtMoney(q.total||0)+'</td><td class="text-end"><div class="warehouse-actions btn-group btn-group-sm"><button class="btn btn-outline-primary quote-detail" data-id="'+esc(q.id)+'" type="button" title="Dettaglio"><i class="fas fa-eye"></i></button><button class="btn btn-outline-danger quote-delete" data-id="'+esc(q.id)+'" type="button" title="Elimina"><i class="fas fa-trash"></i></button></div></td></tr>'); }); }
  function showDetail(id){ const q=getQuotes().find(function(x){return String(x.id)===String(id);}); if(!q) return; const documentLinks = window.DocumentLinksService ? window.DocumentLinksService.renderFor('customer_quote', q) : ''; currentDetailId=String(id); $('#quoteDetailModalTitle').text('Preventivo '+(q.number||'')); const lines=(q.lines||[]).map(function(l){ return '<tr><td>'+esc(l.productCode||'')+'</td><td>'+esc(l.productDescription||l.description||'')+'</td><td>'+esc(l.unitOfMeasure||'pz')+'</td><td class="text-end">'+fmtQty(l.qty)+'</td><td class="text-end">'+fmtMoney(l.price)+'</td><td class="text-end">'+fmtMoney(num(l.qty)*num(l.price))+'</td></tr>'; }).join(''); $('#quoteDetailModalBody').html(documentLinks + '<div class="row g-2 mb-3"><div class="col-md-4"><strong>Cliente:</strong><br>'+esc(q.customerName||'-')+'</div><div class="col-md-2"><strong>Data:</strong><br>'+esc(formatDate(q.date))+'</div><div class="col-md-3"><strong>Valido fino:</strong><br>'+esc(formatDate(q.validUntil))+'</div><div class="col-md-3"><strong>Stato:</strong><br>'+esc(STATUS_LABELS[q.status]||q.status)+'</div></div><table class="table table-sm align-middle"><thead><tr><th>Codice</th><th>Voce</th><th>UM</th><th class="text-end">Q.tà</th><th class="text-end">Prezzo</th><th class="text-end">Totale</th></tr></thead><tbody>'+(lines||'<tr><td colspan="6" class="text-center text-muted">Nessuna riga.</td></tr>')+'</tbody></table><div class="text-end h5">Totale preventivo: '+fmtMoney(q.total||0)+'</div>'+(q.orderId?'<div class="alert alert-success small mt-3">Convertito in ordine cliente '+esc(q.orderNumber||q.orderId)+'.</div>':'<div class="alert alert-info small mt-3">La conversione crea un ordine cliente copiando righe e prezzi; il magazzino non viene movimentato.</div>')+(q.notes?'<div class="alert alert-secondary small mt-3">'+esc(q.notes)+'</div>':'')); $('#convertQuoteToOrderBtn').prop('disabled', !!q.orderId || q.status==='converted' || q.status==='rejected' || q.status==='cancelled'); $('#quoteDetailModal').modal('show'); }
  async function deleteQuote(id){ const q=getQuotes().find(function(x){return String(x.id)===String(id);}); if(!q) return; if(q.orderId || q.status==='converted'){ alert('Preventivo già convertito: eliminazione bloccata in modo prudenziale.'); return; } if(!confirm('Eliminare il preventivo '+(q.number||id)+'?')) return; await window.deleteDataFromCloud('quotes', id, { skipRender:true }); render(); }
  async function convertToOrder(){ const q=getQuotes().find(function(x){return String(x.id)===String(currentDetailId);}); if(!q) return; if(q.orderId || q.status==='converted'){ alert('Preventivo già convertito.'); return; } if(!confirm('Convertire il preventivo '+(q.number||'')+' in ordine cliente?')) return; const orderId=String(getNextOrderId()); const orderNumber=previewOrderNumber(); const now=new Date().toISOString(); const order={ id:orderId, number:orderNumber, date:today(), expectedDeliveryDate:q.validUntil||'', customerId:q.customerId, customerName:q.customerName, status:'confirmed', sourceQuoteId:String(q.id), sourceQuoteNumber:q.number||'', lines:(q.lines||[]).map(function(l){ return Object.assign({},l,{ orderedQty:num(l.qty), fulfilledQty:0, shippedQty:0, remainingQty:num(l.qty), lineTotal:num(l.qty)*num(l.price) }); }), notes:'Creato da preventivo '+(q.number||q.id)+(q.notes?' - '+q.notes:''), createdAt:now, updatedAt:now };
    const normalizedOrder = window.DomainNormalizers && window.DomainNormalizers.normalizeCustomerOrder ? window.DomainNormalizers.normalizeCustomerOrder(order) : order;
    const updatedQuote = Object.assign({}, q, { status:'converted', orderId:orderId, orderNumber:orderNumber, convertedAt:now, updatedAt:now });
    $('#convertQuoteToOrderBtn').prop('disabled',true); await window.saveDataToCloud('customerOrders', normalizedOrder, orderId); await window.saveDataToCloud('quotes', normalizeQuote(updatedQuote), String(q.id)); $('#quoteDetailModal').modal('hide'); render(); if(window.renderCustomerOrdersArea) window.renderCustomerOrdersArea(); }
  function bind(){ if(_bound) return; _bound=true; $('#newQuoteBtn, #menu-nuovo-preventivo-cliente').on('click.quotes', function(e){ if(e) e.preventDefault(); resetForm(); $('#quoteModal').modal('show'); }); $('#quote-productId').on('change.quotes', function(){ $('#quote-linePrice').data('manual',false); syncPrice(); }); $('#quote-linePrice').on('input.quotes', function(){ $(this).data('manual',true); }); $('#addQuoteLineBtn').on('click.quotes', addLine); $('#quote-lines-body').on('click.quotes','.quote-remove-line', function(){ tempLines.splice(parseInt($(this).attr('data-index'),10),1); recalcLines(); }); $('#saveQuoteBtn').on('click.quotes', saveQuote); $('#quotes-table-body').on('click.quotes','.quote-detail', function(){ showDetail($(this).attr('data-id')); }); $('#quotes-table-body').on('click.quotes','.quote-delete', function(){ deleteQuote($(this).attr('data-id')); }); $('#deleteQuoteFromDetailBtn').on('click.quotes', function(){ if(currentDetailId) deleteQuote(currentDetailId).then(function(){ $('#quoteDetailModal').modal('hide'); }); }); $('#convertQuoteToOrderBtn').on('click.quotes', convertToOrder); if(window.AppStore&&typeof window.AppStore.subscribe==='function'){ ['quotes','customers','products','customerOrders'].forEach(function(k){ window.AppStore.subscribe(k, render); }); } render(); }
  window.renderQuotesArea = render;
  window.QuoteService = { normalizeQuote: normalizeQuote, statusLabels: STATUS_LABELS, previewNumber: previewNumber };
  window.AppModules.quotes.bind = bind;
})();
